/*
CREATE TABLE STUDENT_TBL_01
 ( STUDENT_NO INT(11) NOT NULL AUTO_INCREMENT,
 		STUDENT_NAME VARCHAR(20 ),
 		STUDENT_ADDR VARCHAR(100 ),
 		STUDENT_PHONE VARCHAR(14 ),
 		STUDENT_BIRTH DATE,
 		STUDENT_EMAIL VARCHAR(50 ),
 		STUDENT_ID VARCHAR(12 ),
 		STUDENT_PW VARCHAR(50 ),
 		PRIMARY KEY (`STUDENT_NO`)
 );

*/
Insert into STUDENT_TBL_01
(STUDENT_NO,STUDENT_NAME, STUDENT_ADDR, STUDENT_PHONE, STUDENT_BIRTH, STUDENT_EMAIL, STUDENT_ID, STUDENT_PW)
values (201801,'김권수','전라북도 전주시 완산구 효자동','01092799956','2020/01/15','rnjstn123456@naver.com',null,null);

select * from student_tbl_01;